/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MemberRouteImport } from './routes/_member'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as MemberAccountCentreRouteImport } from './routes/_member.account-centre'
import { Route as MemberBillingRouteImport } from './routes/_member.billing'
import { Route as MemberConnectionsRouteImport } from './routes/_member.connections'
import { Route as MemberDiscoverRouteImport } from './routes/_member.discover'
import { Route as MemberEventsRouteImport } from './routes/_member.events'
import { Route as MemberMeRouteImport } from './routes/_member.me'
import { Route as MemberMessagesRouteImport } from './routes/_member.messages'
import { Route as MemberNotificationsRouteImport } from './routes/_member.notifications'
import { Route as MemberSettingsRouteImport } from './routes/_member.settings'
import { Route as MemberStoryRouteImport } from './routes/_member.story'
import { Route as MemberMessagesIndexRouteImport } from './routes/_member.messages.index'
import { Route as MemberMessagesProfileIdRouteImport } from './routes/_member.messages.$profileId'
import { Route as MemberProfileIdRouteImport } from './routes/_member.profile.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberRoute = MemberRouteImport.update({
  id: '/_member',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberAccountCentreRoute = MemberAccountCentreRouteImport.update({
  id: '/account-centre',
  path: '/account-centre',
  getParentRoute: () => MemberRoute,
} as any)
const MemberBillingRoute = MemberBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => MemberRoute,
} as any)
const MemberConnectionsRoute = MemberConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => MemberRoute,
} as any)
const MemberDiscoverRoute = MemberDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => MemberRoute,
} as any)
const MemberEventsRoute = MemberEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => MemberRoute,
} as any)
const MemberMeRoute = MemberMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => MemberRoute,
} as any)
const MemberMessagesRoute = MemberMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => MemberRoute,
} as any)
const MemberNotificationsRoute = MemberNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => MemberRoute,
} as any)
const MemberSettingsRoute = MemberSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MemberRoute,
} as any)
const MemberStoryRoute = MemberStoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => MemberRoute,
} as any)
const MemberMessagesIndexRoute = MemberMessagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MemberMessagesRoute,
} as any)
const MemberMessagesProfileIdRoute = MemberMessagesProfileIdRouteImport.update({
  id: '/$profileId',
  path: '/$profileId',
  getParentRoute: () => MemberMessagesRoute,
} as any)
const MemberProfileIdRoute = MemberProfileIdRouteImport.update({
  id: '/profile/$id',
  path: '/profile/$id',
  getParentRoute: () => MemberRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/account-centre': typeof MemberAccountCentreRoute
  '/billing': typeof MemberBillingRoute
  '/connections': typeof MemberConnectionsRoute
  '/discover': typeof MemberDiscoverRoute
  '/events': typeof MemberEventsRoute
  '/me': typeof MemberMeRoute
  '/messages': typeof MemberMessagesRouteWithChildren
  '/notifications': typeof MemberNotificationsRoute
  '/settings': typeof MemberSettingsRoute
  '/story': typeof MemberStoryRoute
  '/messages/$profileId': typeof MemberMessagesProfileIdRoute
  '/profile/$id': typeof MemberProfileIdRoute
  '/messages/': typeof MemberMessagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/account-centre': typeof MemberAccountCentreRoute
  '/billing': typeof MemberBillingRoute
  '/connections': typeof MemberConnectionsRoute
  '/discover': typeof MemberDiscoverRoute
  '/events': typeof MemberEventsRoute
  '/me': typeof MemberMeRoute
  '/notifications': typeof MemberNotificationsRoute
  '/settings': typeof MemberSettingsRoute
  '/story': typeof MemberStoryRoute
  '/messages/$profileId': typeof MemberMessagesProfileIdRoute
  '/profile/$id': typeof MemberProfileIdRoute
  '/messages': typeof MemberMessagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_member': typeof MemberRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_member/account-centre': typeof MemberAccountCentreRoute
  '/_member/billing': typeof MemberBillingRoute
  '/_member/connections': typeof MemberConnectionsRoute
  '/_member/discover': typeof MemberDiscoverRoute
  '/_member/events': typeof MemberEventsRoute
  '/_member/me': typeof MemberMeRoute
  '/_member/messages': typeof MemberMessagesRouteWithChildren
  '/_member/notifications': typeof MemberNotificationsRoute
  '/_member/settings': typeof MemberSettingsRoute
  '/_member/story': typeof MemberStoryRoute
  '/_member/messages/$profileId': typeof MemberMessagesProfileIdRoute
  '/_member/profile/$id': typeof MemberProfileIdRoute
  '/_member/messages/': typeof MemberMessagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/account-centre'
    | '/billing'
    | '/connections'
    | '/discover'
    | '/events'
    | '/me'
    | '/messages'
    | '/notifications'
    | '/settings'
    | '/story'
    | '/messages/$profileId'
    | '/profile/$id'
    | '/messages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/account-centre'
    | '/billing'
    | '/connections'
    | '/discover'
    | '/events'
    | '/me'
    | '/notifications'
    | '/settings'
    | '/story'
    | '/messages/$profileId'
    | '/profile/$id'
    | '/messages'
  id:
    | '__root__'
    | '/'
    | '/_member'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/_member/account-centre'
    | '/_member/billing'
    | '/_member/connections'
    | '/_member/discover'
    | '/_member/events'
    | '/_member/me'
    | '/_member/messages'
    | '/_member/notifications'
    | '/_member/settings'
    | '/_member/story'
    | '/_member/messages/$profileId'
    | '/_member/profile/$id'
    | '/_member/messages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MemberRoute: typeof MemberRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_member': {
      id: '/_member'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MemberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_member/account-centre': {
      id: '/_member/account-centre'
      path: '/account-centre'
      fullPath: '/account-centre'
      preLoaderRoute: typeof MemberAccountCentreRouteImport
      parentRoute: typeof MemberRoute
    }
    '/_member/billing': {
      id: '/_member/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof MemberBillingRouteImport
      parentRoute: typeof MemberRoute
    }
    '/_member/connections': {
      id: '/_member/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof MemberConnectionsRouteImport
      parentRoute: typeof MemberRoute
    }
    '/_member/discover': {
      id: '/_member/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof MemberDiscoverRouteImport
      parentRoute: typeof MemberRoute
    }
    '/_member/events': {
      id: '/_member/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof MemberEventsRouteImport
      parentRoute: typeof MemberRoute
    }
    '/_member/me': {
      id: '/_member/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MemberMeRouteImport
      parentRoute: typeof MemberRoute
    }
    '/_member/messages': {
      id: '/_member/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MemberMessagesRouteImport
      parentRoute: typeof MemberRoute
    }
    '/_member/notifications': {
      id: '/_member/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof MemberNotificationsRouteImport
      parentRoute: typeof MemberRoute
    }
    '/_member/settings': {
      id: '/_member/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof MemberSettingsRouteImport
      parentRoute: typeof MemberRoute
    }
    '/_member/story': {
      id: '/_member/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof MemberStoryRouteImport
      parentRoute: typeof MemberRoute
    }
    '/_member/messages/': {
      id: '/_member/messages/'
      path: '/'
      fullPath: '/messages/'
      preLoaderRoute: typeof MemberMessagesIndexRouteImport
      parentRoute: typeof MemberMessagesRoute
    }
    '/_member/messages/$profileId': {
      id: '/_member/messages/$profileId'
      path: '/$profileId'
      fullPath: '/messages/$profileId'
      preLoaderRoute: typeof MemberMessagesProfileIdRouteImport
      parentRoute: typeof MemberMessagesRoute
    }
    '/_member/profile/$id': {
      id: '/_member/profile/$id'
      path: '/profile/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof MemberProfileIdRouteImport
      parentRoute: typeof MemberRoute
    }
  }
}

interface MemberMessagesRouteChildren {
  MemberMessagesProfileIdRoute: typeof MemberMessagesProfileIdRoute
  MemberMessagesIndexRoute: typeof MemberMessagesIndexRoute
}

const MemberMessagesRouteChildren: MemberMessagesRouteChildren = {
  MemberMessagesProfileIdRoute: MemberMessagesProfileIdRoute,
  MemberMessagesIndexRoute: MemberMessagesIndexRoute,
}

const MemberMessagesRouteWithChildren = MemberMessagesRoute._addFileChildren(
  MemberMessagesRouteChildren,
)

interface MemberRouteChildren {
  MemberAccountCentreRoute: typeof MemberAccountCentreRoute
  MemberBillingRoute: typeof MemberBillingRoute
  MemberConnectionsRoute: typeof MemberConnectionsRoute
  MemberDiscoverRoute: typeof MemberDiscoverRoute
  MemberEventsRoute: typeof MemberEventsRoute
  MemberMeRoute: typeof MemberMeRoute
  MemberMessagesRoute: typeof MemberMessagesRouteWithChildren
  MemberNotificationsRoute: typeof MemberNotificationsRoute
  MemberSettingsRoute: typeof MemberSettingsRoute
  MemberStoryRoute: typeof MemberStoryRoute
  MemberProfileIdRoute: typeof MemberProfileIdRoute
}

const MemberRouteChildren: MemberRouteChildren = {
  MemberAccountCentreRoute: MemberAccountCentreRoute,
  MemberBillingRoute: MemberBillingRoute,
  MemberConnectionsRoute: MemberConnectionsRoute,
  MemberDiscoverRoute: MemberDiscoverRoute,
  MemberEventsRoute: MemberEventsRoute,
  MemberMeRoute: MemberMeRoute,
  MemberMessagesRoute: MemberMessagesRouteWithChildren,
  MemberNotificationsRoute: MemberNotificationsRoute,
  MemberSettingsRoute: MemberSettingsRoute,
  MemberStoryRoute: MemberStoryRoute,
  MemberProfileIdRoute: MemberProfileIdRoute,
}

const MemberRouteWithChildren =
  MemberRoute._addFileChildren(MemberRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MemberRoute: MemberRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
